//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WexProject.Schedule.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WexProject.Schedule.Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _32x32 {
            get {
                object obj = ResourceManager.GetObject("_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _32x32_Nova_Tarefa {
            get {
                object obj = ResourceManager.GetObject("_32x32_Nova_Tarefa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _32x32_Pesquisa_Personalizado {
            get {
                object obj = ResourceManager.GetObject("32x32_Pesquisa_Personalizado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _32x32_Pesquisar_Tudo {
            get {
                object obj = ResourceManager.GetObject("_32x32_Pesquisar_Tudo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _32x32_Tarefas_Encerradas {
            get {
                object obj = ResourceManager.GetObject("_32x32_Tarefas_Encerradas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _32x32_Tarefas_Pendentes {
            get {
                object obj = ResourceManager.GetObject("_32x32_Tarefas_Pendentes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap alert_popup32x32 {
            get {
                object obj = ResourceManager.GetObject("alert_popup32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaborador não existente, contate o administrador..
        /// </summary>
        public static string Alerta_ColaboradorInvalido {
            get {
                return ResourceManager.GetString("Alerta_ColaboradorInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente excluir as tarefas selecionadas?.
        /// </summary>
        public static string Alerta_ConfirmarExclusaoTarefasSelecionadas {
            get {
                return ResourceManager.GetString("Alerta_ConfirmarExclusaoTarefasSelecionadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conexão com servidor foi interrompida..
        /// </summary>
        public static string Alerta_Desconectado {
            get {
                return ResourceManager.GetString("Alerta_Desconectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma estimativa inicial deve ser informada..
        /// </summary>
        public static string Alerta_DevePossuirDuracaoTarefa {
            get {
                return ResourceManager.GetString("Alerta_DevePossuirDuracaoTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A edição da tarefa não pode ser salva..
        /// </summary>
        public static string Alerta_EdicaoNaoSalva {
            get {
                return ResourceManager.GetString("Alerta_EdicaoNaoSalva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível editar a tarefa, pois se encontra em exclusão..
        /// </summary>
        public static string Alerta_EdicaoRecusadaTarefaEmExclusao {
            get {
                return ResourceManager.GetString("Alerta_EdicaoRecusadaTarefaEmExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente fechar o cronograma?.
        /// </summary>
        public static string Alerta_Fechar_Cronograma {
            get {
                return ResourceManager.GetString("Alerta_Fechar_Cronograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um cronograma com esse nome..
        /// </summary>
        public static string Alerta_JaExisteCronogramaComEsseNome {
            get {
                return ResourceManager.GetString("Alerta_JaExisteCronogramaComEsseNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você já possui uma edição de tarefa em andamento..
        /// </summary>
        public static string Alerta_JaPossuiTarefaEmEdicao {
            get {
                return ResourceManager.GetString("Alerta_JaPossuiTarefaEmEdicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe um cronograma selecionado para exclusão..
        /// </summary>
        public static string Alerta_NaoExisteCronogramaParaExclusao {
            get {
                return ResourceManager.GetString("Alerta_NaoExisteCronogramaParaExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não pode criar cronogramas se não houver criado uma situação de planejamento padrão..
        /// </summary>
        public static string Alerta_NaoExisteSituacaoPlanejamento {
            get {
                return ResourceManager.GetString("Alerta_NaoExisteSituacaoPlanejamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe situação de planejamento ativa. 
        ///Não é possível acessar o cronograma..
        /// </summary>
        public static string Alerta_NaoExisteSituacaoPlanejamentoAtiva {
            get {
                return ResourceManager.GetString("Alerta_NaoExisteSituacaoPlanejamentoAtiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tarefa selecionada não possui histórico..
        /// </summary>
        public static string Alerta_NaoHaHistorico {
            get {
                return ResourceManager.GetString("Alerta_NaoHaHistorico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do nome do cronograma é obrigatório..
        /// </summary>
        public static string Alerta_NomeCronogramaObrigatorio {
            get {
                return ResourceManager.GetString("Alerta_NomeCronogramaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tarefa já possui esforço estimado..
        /// </summary>
        public static string Alerta_PossuiEsforcoRealizadoCadastrado {
            get {
                return ResourceManager.GetString("Alerta_PossuiEsforcoRealizadoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do cronograma não é válida.
        ///A descrição poderá conter apenas letras, números, sublinhados, espaços, pontos e traços..
        /// </summary>
        public static string Alerta_PreenchimentoNomeCronograma {
            get {
                return ResourceManager.GetString("Alerta_PreenchimentoNomeCronograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A situação de planejamento informada não é válida..
        /// </summary>
        public static string Alerta_SituacaoPlanejamentoInvalida {
            get {
                return ResourceManager.GetString("Alerta_SituacaoPlanejamentoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A situação de planejamento informada não é válida com relação à estimativa das horas,  revise a estimativa..
        /// </summary>
        public static string Alerta_SituacaoPlanejamentoInvalidaAoSalvar {
            get {
                return ResourceManager.GetString("Alerta_SituacaoPlanejamentoInvalidaAoSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao menos uma tarefa deve ser selecionada para exclusão..
        /// </summary>
        public static string Alerta_TarefaNaoSelecionadaParaExclusao {
            get {
                return ResourceManager.GetString("Alerta_TarefaNaoSelecionadaParaExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção.
        /// </summary>
        public static string Caption_Atencao {
            get {
                return ResourceManager.GetString("Caption_Atencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string Caption_Erro {
            get {
                return ResourceManager.GetString("Caption_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao excluir o cronograma..
        /// </summary>
        public static string Caption_ErroExclusaoCronograma {
            get {
                return ResourceManager.GetString("Caption_ErroExclusaoCronograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string Caption_Fechar {
            get {
                return ResourceManager.GetString("Caption_Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação de planejamento informada não é válida..
        /// </summary>
        public static string Caption_SituacaoPlanejamentoInvalida {
            get {
                return ResourceManager.GetString("Caption_SituacaoPlanejamentoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap doc2_16x16 {
            get {
                object obj = ResourceManager.GetObject("doc2_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir um cronograma com outros colaboradores conectados..
        /// </summary>
        public static string Erro_ExcluirCronogramaComColaboradoresConectados {
            get {
                return ResourceManager.GetString("Erro_ExcluirCronogramaComColaboradoresConectados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir um cronograma que contenha tarefas com esforço estimado..
        /// </summary>
        public static string Erro_ExcluirCronogramaQuePossuaTarefas {
            get {
                return ResourceManager.GetString("Erro_ExcluirCronogramaQuePossuaTarefas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível efetuar conexão com o servidor, contate o administrador do sistema..
        /// </summary>
        public static string Erro_FalhaConexao {
            get {
                return ResourceManager.GetString("Erro_FalhaConexao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap excluir {
            get {
                object obj = ResourceManager.GetObject("excluir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imagemPadrao {
            get {
                object obj = ResourceManager.GetObject("imagemPadrao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cronograma conectado..
        /// </summary>
        public static string Info_Conectado {
            get {
                return ResourceManager.GetString("Info_Conectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cronograma desconectado..
        /// </summary>
        public static string Info_Desconectado {
            get {
                return ResourceManager.GetString("Info_Desconectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.0.0.28.
        /// </summary>
        public static string IpServidor {
            get {
                return ResourceManager.GetString("IpServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to juca.pereira.
        /// </summary>
        public static string LoginDefault {
            get {
                return ResourceManager.GetString("LoginDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap None {
            get {
                object obj = ResourceManager.GetObject("None", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap seta_abaixo {
            get {
                object obj = ResourceManager.GetObject("seta_abaixo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap seta_abaixo3264 {
            get {
                object obj = ResourceManager.GetObject("seta_abaixo3264", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap seta_acima {
            get {
                object obj = ResourceManager.GetObject("seta_acima", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap seta_acima3264 {
            get {
                object obj = ResourceManager.GetObject("seta_acima3264", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon WexCronograma {
            get {
                object obj = ResourceManager.GetObject("WexCronograma", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
