// <auto-generated />
namespace WexProject.BLL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class GastosModificado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GastosModificado));
        
        string IMigrationMetadata.Id
        {
            get { return "201307252028050_GastosModificado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
