// <auto-generated />
namespace WexProject.BLL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CriacaoTarefaHistoricoEstimativa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriacaoTarefaHistoricoEstimativa));
        
        string IMigrationMetadata.Id
        {
            get { return "201405081951566_CriacaoTarefaHistoricoEstimativa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
