//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WexProject.BLL.Contexto.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTOSRH
    {
        public string RA_FILIAL { get; set; }
        public string RA_MAT { get; set; }
        public string RA_NOME { get; set; }
        public string RA_CC { get; set; }
        public string RA_ADMISSA { get; set; }
        public string RA_DEMISSA { get; set; }
        public string RA_CATFUNC { get; set; }
        public string RA_SITFOLH { get; set; }
        public Nullable<double> RA_SALARIO { get; set; }
        public string RA_CODFUNC { get; set; }
        public string RJ_DESC { get; set; }
        public string RD_CC { get; set; }
        public string ANOMES { get; set; }
        public Nullable<double> FOL_PROV { get; set; }
        public Nullable<double> FOL_DESC { get; set; }
        public Nullable<double> FER_PROV { get; set; }
        public Nullable<double> FER_DESC { get; set; }
        public Nullable<double> P13_PROV { get; set; }
        public Nullable<double> P13_DESC { get; set; }
        public Nullable<double> PD799 { get; set; }
        public Nullable<double> INSS { get; set; }
        public Nullable<double> FGTS { get; set; }
        public Nullable<double> PIS { get; set; }
        public Nullable<double> ENCARGOS { get; set; }
        public Nullable<double> PLSAUDE { get; set; }
        public Nullable<double> PLODONT { get; set; }
        public Nullable<double> AUX_ALIM { get; set; }
        public Nullable<double> AUX_OUT { get; set; }
        public Nullable<double> AUX_REF { get; set; }
        public Nullable<double> AUX_TRANSP { get; set; }
        public Nullable<double> BENEFICIOS { get; set; }
        public Nullable<double> PROVFER { get; set; }
        public Nullable<double> PROV13o { get; set; }
        public Nullable<double> PROVTOT { get; set; }
        public Nullable<double> PROVDEM { get; set; }
        public Nullable<double> PROVISAO { get; set; }
        public Nullable<double> TOTALFIM { get; set; }
        public Nullable<double> PERCCUSTO { get; set; }
        public double CONTROLE { get; set; }
        public string FLAG { get; set; }
        public int CHAVE { get; set; }
    }
}
