//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WexProject.BLL.Contexto.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBRICA
    {
        public string FILIAL { get; set; }
        public System.DateTime DATA { get; set; }
        public string LOTE { get; set; }
        public string SUBLOTE { get; set; }
        public string DOCUMENTO { get; set; }
        public string LINHA { get; set; }
        public string EMPORI { get; set; }
        public string FILORI { get; set; }
        public string MOEDLC { get; set; }
        public string SEQIDX { get; set; }
        public string ANOMES { get; set; }
        public string TP_LANC { get; set; }
        public string CENTRO_CUSTO { get; set; }
        public string DESC_CC { get; set; }
        public string CONTA_CONTABIL { get; set; }
        public string DESC_CCONTABIL { get; set; }
        public string MATRICULA { get; set; }
        public string HIST_LANC { get; set; }
        public double VALOR_CREDITO { get; set; }
        public double VALOR_DEBITO { get; set; }
        public double CONTROLE { get; set; }
        public string FLAG { get; set; }
        public int CHAVE { get; set; }
    }
}
