// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18052
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace WexProject.Test.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ManterOsDadosDaEstoriaAoClicarNoBotaoSalvarENovoFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AnalistaNegociosManterDadosEstoria.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Manter os dados da estoria ao clicar no botão salvar e novo", "Como um Analista de Negócios\r\nEu quero manter os alguns dados da estoria selecion" +
                    "ada após clicar em salvar e novo\r\nPara que seja agilizado o processo de digitaçã" +
                    "o de estoorias relacionadas", ProgrammingLanguage.CSharp, new string[] {
                        "pbi_2.11"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Manter os dados da estoria ao clicar no botão salvar e novo")))
            {
                WexProject.Test.Features.ManterOsDadosDaEstoriaAoClicarNoBotaoSalvarENovoFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("01 - Ao clicar no botão Salvar e Novo, manter os dados dos campos \'Como um\', \'Sol" +
            "icitante\', \'Módulo\' e \'Estoria Pai\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Manter os dados da estoria ao clicar no botão salvar e novo")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("pbi_2.11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("rn")]
        public virtual void _01_AoClicarNoBotaoSalvarENovoManterOsDadosDosCamposComoUmSolicitanteModuloEEstoriaPai()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 - Ao clicar no botão Salvar e Novo, manter os dados dos campos \'Como um\', \'Sol" +
                    "icitante\', \'Módulo\' e \'Estoria Pai\'", new string[] {
                        "rn"});
#line 10
this.ScenarioSetup(scenarioInfo);
#line 11
   testRunner.Given("o módulo \'2 - Escopo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 12
  testRunner.And("o módulo \'1 - Teste\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 13
  testRunner.And("benefeciado \'Analista de Negocios\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 14
  testRunner.And("benefeciado \'Desenvolvedor\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 15
  testRunner.And("parte interessada \'Alexandre Amorim\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "Titulo",
                        ""});
            table1.AddRow(new string[] {
                        "EstoriaPai",
                        ""});
            table1.AddRow(new string[] {
                        "ComoUm",
                        "Desenvolvedor"});
            table1.AddRow(new string[] {
                        "Solicitante",
                        ""});
            table1.AddRow(new string[] {
                        "Modulo",
                        "1 - Teste"});
#line 16
  testRunner.And("a estoria \'estoria00\' com as seguintes propriedades:", ((string)(null)), table1, "E ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "Titulo",
                        "Estoria_01"});
            table2.AddRow(new string[] {
                        "EstoriaPai",
                        "estoria00"});
            table2.AddRow(new string[] {
                        "ComoUm",
                        "Analista de Negocios"});
            table2.AddRow(new string[] {
                        "Solicitante",
                        "Alexandre Amorim"});
            table2.AddRow(new string[] {
                        "Modulo",
                        "2 - Escopo"});
#line 23
  testRunner.And("a estoria \'estoria01\' com as seguintes propriedades:", ((string)(null)), table2, "E ");
#line 30
   testRunner.When("clicar em salvar e novo da estoria \'estoria01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table3.AddRow(new string[] {
                        "Titulo",
                        ""});
            table3.AddRow(new string[] {
                        "EstoriaPai",
                        "estoria00"});
            table3.AddRow(new string[] {
                        "ComoUm",
                        "Analista de Negocios"});
            table3.AddRow(new string[] {
                        "Solicitante",
                        "Alexandre Amorim"});
            table3.AddRow(new string[] {
                        "Modulo",
                        "2 - Escopo"});
#line 31
  testRunner.Then("a nova estoria deve estar com as seguintes propiedades:", ((string)(null)), table3, "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
