// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.32559
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace WexProject.Test.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Analista de RH Visualizar Férias Planejadas Para Determinado Periodo")]
    [NUnit.Framework.CategoryAttribute("pbi_10.01.03")]
    public partial class AnalistaDeRHVisualizarFeriasPlanejadasParaDeterminadoPeriodoFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AnalistaRHVisualizarFeriasPlanejadasParaDeterminadoPeriodo.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Analista de RH Visualizar Férias Planejadas Para Determinado Periodo", "Como um Analista de RH\r\nQuero que seja possível visualizar, cadastrar, alterar e " +
                    "excluír planejamento de férias para os colaboradores.\r\nDeve ser possível filtrar" +
                    " os dados por um ou mais superior imediato e por período.", ProgrammingLanguage.CSharp, new string[] {
                        "pbi_10.01.03"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 9
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "dias",
                        "pode vender",
                        "ativo"});
            table1.AddRow(new string[] {
                        "30",
                        "nao",
                        "sim"});
            table1.AddRow(new string[] {
                        "90",
                        "nao",
                        "sim"});
#line 10
     testRunner.Given("existam as modalidades de ferias:", ((string)(null)), table1, "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "nome",
                        "tamanho",
                        "total de ciclos",
                        "ritmo do time"});
            table2.AddRow(new string[] {
                        "Projeto01",
                        "50",
                        "5",
                        "10"});
            table2.AddRow(new string[] {
                        "Projeto02",
                        "50",
                        "5",
                        "10"});
#line 14
  testRunner.And("que exista(m) o(s) projeto(s) a seguir:", ((string)(null)), table2, "E ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01 - Listar os planejamentos de ferias filtrados por periodo.")]
        public virtual void _01_ListarOsPlanejamentosDeFeriasFiltradosPorPeriodo_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 - Listar os planejamentos de ferias filtrados por periodo.", ((string[])(null)));
#line 19
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "superior",
                        "admissao"});
            table3.AddRow(new string[] {
                        "colab 1",
                        "",
                        "01/01/2011"});
            table3.AddRow(new string[] {
                        "colab 2",
                        "",
                        "01/01/2011"});
            table3.AddRow(new string[] {
                        "colab 1.1",
                        "colab 1",
                        "01/01/2011"});
            table3.AddRow(new string[] {
                        "colab 2.1",
                        "colab 2",
                        "01/01/2011"});
#line 20
 testRunner.Given("que existam os colaboradores:", ((string)(null)), table3, "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "cargo"});
            table4.AddRow(new string[] {
                        "colab 1.1",
                        "Analista"});
#line 26
   testRunner.And("existam as seguintes partes interessadas para o projeto \'Projeto01\':", ((string)(null)), table4, "E ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "data inicial",
                        "modalidade"});
            table5.AddRow(new string[] {
                        "colab 1.1",
                        "01/01/2012",
                        "30"});
            table5.AddRow(new string[] {
                        "colab 2.1",
                        "01/01/2012",
                        "30"});
#line 29
   testRunner.And("que existam os seguintes planejamentos de ferias:", ((string)(null)), table5, "E ");
#line 33
  testRunner.When("consultar o planejamento de ferias no periodo de \'01/2012\' a \'12/2012\':", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "superior",
                        "projeto"});
            table6.AddRow(new string[] {
                        "colab 1.1",
                        "colab 1",
                        "Projeto01"});
            table6.AddRow(new string[] {
                        "colab 2.1",
                        "colab 2",
                        "Sem Projeto"});
#line 34
   testRunner.Then("devem ser listados no plenejamento de ferias os colaboradores:", ((string)(null)), table6, "Entao ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "data inicial",
                        "modalidade"});
            table7.AddRow(new string[] {
                        "colab 1.1",
                        "01/01/2012",
                        "30"});
            table7.AddRow(new string[] {
                        "colab 2.1",
                        "01/01/2012",
                        "30"});
#line 38
      testRunner.And("devem ser listados os planejamentos de ferias:", ((string)(null)), table7, "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02 - Listar os planejamentos de ferias filtrados por periodo e superior imediato." +
            "")]
        public virtual void _02_ListarOsPlanejamentosDeFeriasFiltradosPorPeriodoESuperiorImediato_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 - Listar os planejamentos de ferias filtrados por periodo e superior imediato." +
                    "", ((string[])(null)));
#line 43
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "superior",
                        "admissao"});
            table8.AddRow(new string[] {
                        "colab 1",
                        "",
                        "01/01/2011"});
            table8.AddRow(new string[] {
                        "colab 2",
                        "",
                        "01/01/2011"});
            table8.AddRow(new string[] {
                        "colab 1.1",
                        "colab 1",
                        "01/01/2011"});
            table8.AddRow(new string[] {
                        "colab 2.1",
                        "colab 2",
                        "01/01/2011"});
#line 44
    testRunner.Given("que existam os colaboradores:", ((string)(null)), table8, "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "cargo"});
            table9.AddRow(new string[] {
                        "colab 1.1",
                        "Analista"});
#line 50
    testRunner.And("existam as seguintes partes interessadas para o projeto \'Projeto01\':", ((string)(null)), table9, "E ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "data inicial",
                        "modalidade"});
            table10.AddRow(new string[] {
                        "colab 1.1",
                        "01/01/2012",
                        "30"});
            table10.AddRow(new string[] {
                        "colab 2.1",
                        "01/01/2012",
                        "30"});
#line 53
    testRunner.And("que existam os seguintes planejamentos de ferias:", ((string)(null)), table10, "E ");
#line 57
  testRunner.When("consultar o planejamento de ferias no periodo de \'01/2012\' a \'02/2012\' filtrando " +
                    "pelos superiores imediatos \'colab 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "superior",
                        "projeto"});
            table11.AddRow(new string[] {
                        "colab 1.1",
                        "colab 1",
                        "projeto 01"});
#line 58
   testRunner.Then("devem ser listados no plenejamento de ferias os colaboradores:", ((string)(null)), table11, "Entao ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "data inicial",
                        "modalidade"});
            table12.AddRow(new string[] {
                        "colab 1.1",
                        "01/01/2012",
                        "30"});
#line 61
       testRunner.And("devem ser listados os planejamentos de ferias:", ((string)(null)), table12, "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03 - Listar os planejamentos de ferias filtrados por periodo e varios superiores " +
            "imediatos.")]
        public virtual void _03_ListarOsPlanejamentosDeFeriasFiltradosPorPeriodoEVariosSuperioresImediatos_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 - Listar os planejamentos de ferias filtrados por periodo e varios superiores " +
                    "imediatos.", ((string[])(null)));
#line 65
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "superior",
                        "admissao"});
            table13.AddRow(new string[] {
                        "colab 1",
                        "",
                        "01/01/2011"});
            table13.AddRow(new string[] {
                        "colab 2",
                        "",
                        "01/01/2011"});
            table13.AddRow(new string[] {
                        "colab 3",
                        "",
                        "01/01/2011"});
            table13.AddRow(new string[] {
                        "colab 1.1",
                        "colab 1",
                        "01/01/2011"});
            table13.AddRow(new string[] {
                        "colab 2.1",
                        "colab 2",
                        "01/01/2011"});
            table13.AddRow(new string[] {
                        "colab 3.1",
                        "colab 3",
                        "01/01/2011"});
#line 66
    testRunner.Given("que existam os colaboradores:", ((string)(null)), table13, "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "cargo"});
            table14.AddRow(new string[] {
                        "colab 1.1",
                        "Analista"});
#line 74
    testRunner.And("existam as seguintes partes interessadas para o projeto \'Projeto01\':", ((string)(null)), table14, "E ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "data inicial",
                        "modalidade"});
            table15.AddRow(new string[] {
                        "colab 1.1",
                        "01/01/2012",
                        "30"});
            table15.AddRow(new string[] {
                        "colab 2.1",
                        "01/01/2012",
                        "30"});
            table15.AddRow(new string[] {
                        "colab 3.1",
                        "01/01/2012",
                        "30"});
#line 77
    testRunner.And("que existam os seguintes planejamentos de ferias:", ((string)(null)), table15, "E ");
#line 82
  testRunner.When("consultar o planejamento de ferias no periodo de \'01/2012\' a \'02/2012\' filtrando " +
                    "pelos superiores imediatos \'colab 1\',\'colab 2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "superior",
                        "projeto"});
            table16.AddRow(new string[] {
                        "colab 1.1",
                        "colab 1",
                        "projeto 01"});
            table16.AddRow(new string[] {
                        "colab 2.1",
                        "colab 2",
                        "Sem Projeto"});
#line 83
   testRunner.Then("devem ser listados no plenejamento de ferias os colaboradores:", ((string)(null)), table16, "Entao ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "data inicial",
                        "modalidade"});
            table17.AddRow(new string[] {
                        "colab 1.1",
                        "01/01/2012",
                        "30"});
            table17.AddRow(new string[] {
                        "colab 2.1",
                        "01/01/2012",
                        "30"});
#line 87
       testRunner.And("devem ser listados os planejamentos de ferias:", ((string)(null)), table17, "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04 - Listar os planejamentos de ferias filtrados por periodo.")]
        public virtual void _04_ListarOsPlanejamentosDeFeriasFiltradosPorPeriodo_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04 - Listar os planejamentos de ferias filtrados por periodo.", ((string[])(null)));
#line 92
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "superior",
                        "admissao"});
            table18.AddRow(new string[] {
                        "colab 1",
                        "",
                        "01/01/2011"});
            table18.AddRow(new string[] {
                        "colab 2",
                        "",
                        "01/01/2011"});
            table18.AddRow(new string[] {
                        "colab 3",
                        "",
                        "01/01/2011"});
            table18.AddRow(new string[] {
                        "colab 1.1",
                        "colab 1",
                        "01/01/2011"});
            table18.AddRow(new string[] {
                        "colab 2.1",
                        "colab 2",
                        "01/01/2011"});
            table18.AddRow(new string[] {
                        "colab 3.1",
                        "colab 3",
                        "01/01/2011"});
#line 93
    testRunner.Given("que existam os colaboradores:", ((string)(null)), table18, "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "cargo"});
            table19.AddRow(new string[] {
                        "colab 1.1",
                        "Analista"});
#line 101
    testRunner.And("existam as seguintes partes interessadas para o projeto \'Projeto01\':", ((string)(null)), table19, "E ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "data inicial",
                        "modalidade"});
            table20.AddRow(new string[] {
                        "colab 1.1",
                        "01/01/2012",
                        "30"});
            table20.AddRow(new string[] {
                        "colab 2.1",
                        "01/02/2012",
                        "30"});
            table20.AddRow(new string[] {
                        "colab 3.1",
                        "01/03/2012",
                        "30"});
#line 104
    testRunner.And("que existam os seguintes planejamentos de ferias:", ((string)(null)), table20, "E ");
#line 109
  testRunner.When("consultar o planejamento de ferias no periodo de \'01/2012\' a \'02/2012\':", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "superior",
                        "projeto"});
            table21.AddRow(new string[] {
                        "colab 1.1",
                        "colab 1",
                        "projeto 01"});
            table21.AddRow(new string[] {
                        "colab 2.1",
                        "colab 2",
                        "Sem Projeto"});
#line 110
   testRunner.Then("devem ser listados no plenejamento de ferias os colaboradores:", ((string)(null)), table21, "Entao ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "data inicial",
                        "modalidade"});
            table22.AddRow(new string[] {
                        "colab 1.1",
                        "01/01/2012",
                        "30"});
            table22.AddRow(new string[] {
                        "colab 2.1",
                        "01/02/2012",
                        "30"});
#line 114
       testRunner.And("devem ser listados os planejamentos de ferias:", ((string)(null)), table22, "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05 - Listar os planejamentos de ferias dos colaboradores visiveis.")]
        public virtual void _05_ListarOsPlanejamentosDeFeriasDosColaboradoresVisiveis_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 - Listar os planejamentos de ferias dos colaboradores visiveis.", ((string[])(null)));
#line 119
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "superior",
                        "admissao"});
            table23.AddRow(new string[] {
                        "colab 1",
                        "",
                        "01/01/2011"});
            table23.AddRow(new string[] {
                        "colab 2",
                        "",
                        "01/01/2011"});
            table23.AddRow(new string[] {
                        "colab 3",
                        "",
                        "01/01/2011"});
            table23.AddRow(new string[] {
                        "colab 1.1",
                        "colab 1",
                        "01/01/2011"});
            table23.AddRow(new string[] {
                        "colab 2.1",
                        "colab 2",
                        "01/01/2011"});
            table23.AddRow(new string[] {
                        "colab 2.2",
                        "colab 2",
                        "01/01/2011"});
            table23.AddRow(new string[] {
                        "colab 3.1",
                        "colab 3",
                        "01/01/2011"});
#line 120
    testRunner.Given("que existam os colaboradores:", ((string)(null)), table23, "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "cargo"});
            table24.AddRow(new string[] {
                        "colab 1.1",
                        "Analista"});
            table24.AddRow(new string[] {
                        "colab 2.1",
                        "Analista"});
#line 129
    testRunner.And("existam as seguintes partes interessadas para o projeto \'Projeto01\':", ((string)(null)), table24, "E ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "cargo"});
            table25.AddRow(new string[] {
                        "colab 3.1",
                        "Analista"});
#line 133
    testRunner.And("existam as seguintes partes interessadas para o projeto \'Projeto02\':", ((string)(null)), table25, "E ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "data inicial",
                        "modalidade"});
            table26.AddRow(new string[] {
                        "colab 1.1",
                        "01/01/2012",
                        "30"});
            table26.AddRow(new string[] {
                        "colab 2.1",
                        "01/01/2012",
                        "30"});
            table26.AddRow(new string[] {
                        "colab 3.1",
                        "01/01/2012",
                        "30"});
#line 136
    testRunner.And("que existam os seguintes planejamentos de ferias:", ((string)(null)), table26, "E ");
#line 141
  testRunner.When("consultar o planejamento de ferias no periodo de \'01/2012\' a \'12/2012\':", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 142
       testRunner.And("ocultar os dados do \'Projeto02\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "superior",
                        "projeto"});
            table27.AddRow(new string[] {
                        "colab 1.1",
                        "colab 1",
                        "projeto 01"});
            table27.AddRow(new string[] {
                        "colab 2.1",
                        "colab 2",
                        "projeto 01"});
#line 143
   testRunner.Then("devem ser listados no plenejamento de ferias os colaboradores:", ((string)(null)), table27, "Entao ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "data inicial",
                        "modalidade"});
            table28.AddRow(new string[] {
                        "colab 1.1",
                        "01/01/2012",
                        "30"});
            table28.AddRow(new string[] {
                        "colab 2.1",
                        "01/02/2012",
                        "30"});
#line 147
       testRunner.And("devem ser listados os planejamentos de ferias:", ((string)(null)), table28, "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06 - Listar os planejamentos de ferias todos os periodos.")]
        public virtual void _06_ListarOsPlanejamentosDeFeriasTodosOsPeriodos_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06 - Listar os planejamentos de ferias todos os periodos.", ((string[])(null)));
#line 153
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "superior",
                        "admissao"});
            table29.AddRow(new string[] {
                        "colab 1",
                        "",
                        "01/01/2011"});
            table29.AddRow(new string[] {
                        "colab 2",
                        "",
                        "01/01/2011"});
            table29.AddRow(new string[] {
                        "colab 3",
                        "",
                        "01/01/2011"});
            table29.AddRow(new string[] {
                        "colab 1.1",
                        "colab 1",
                        "01/01/2011"});
            table29.AddRow(new string[] {
                        "colab 2.1",
                        "colab 2",
                        "01/01/2011"});
            table29.AddRow(new string[] {
                        "colab 2.2",
                        "colab 2",
                        "01/01/2011"});
            table29.AddRow(new string[] {
                        "colab 3.1",
                        "colab 3",
                        "01/01/2011"});
            table29.AddRow(new string[] {
                        "colab 3.2",
                        "colab 3",
                        "01/01/2011"});
#line 154
    testRunner.Given("que existam os colaboradores:", ((string)(null)), table29, "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "cargo"});
            table30.AddRow(new string[] {
                        "colab 1.1",
                        "Analista"});
            table30.AddRow(new string[] {
                        "colab 2.1",
                        "Analista"});
#line 164
    testRunner.And("existam as seguintes partes interessadas para o projeto \'Projeto01\':", ((string)(null)), table30, "E ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "cargo"});
            table31.AddRow(new string[] {
                        "colab 2.2",
                        "Analista"});
            table31.AddRow(new string[] {
                        "colab 3.1",
                        "Analista"});
#line 168
    testRunner.And("existam as seguintes partes interessadas para o projeto \'Projeto02\':", ((string)(null)), table31, "E ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "data inicial",
                        "modalidade"});
            table32.AddRow(new string[] {
                        "colab 1.1",
                        "20/02/2012",
                        "30"});
            table32.AddRow(new string[] {
                        "colab 2.1",
                        "01/03/2012",
                        "30"});
            table32.AddRow(new string[] {
                        "colab 2.2",
                        "20/03/2012",
                        "30"});
            table32.AddRow(new string[] {
                        "colab 3.1",
                        "01/02/2012",
                        "90"});
            table32.AddRow(new string[] {
                        "colab 3.2",
                        "01/01/2012",
                        "30"});
#line 172
    testRunner.And("que existam os seguintes planejamentos de ferias:", ((string)(null)), table32, "E ");
#line 179
  testRunner.When("consultar o planejamento de ferias no periodo de \'03/2012\' a \'03/2012\':", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "superior",
                        "projeto"});
            table33.AddRow(new string[] {
                        "colab 1.1",
                        "colab 1",
                        "projeto 01"});
            table33.AddRow(new string[] {
                        "colab 2.1",
                        "colab 1",
                        "projeto 01"});
            table33.AddRow(new string[] {
                        "colab 2.2",
                        "colab 2",
                        "projeto 02"});
            table33.AddRow(new string[] {
                        "colab 3.1",
                        "colab 3",
                        "projeto 02"});
#line 180
   testRunner.Then("devem ser listados no plenejamento de ferias os colaboradores:", ((string)(null)), table33, "Entao ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "data inicial",
                        "modalidade"});
            table34.AddRow(new string[] {
                        "colab 1.1",
                        "20/02/2012",
                        "30"});
            table34.AddRow(new string[] {
                        "colab 2.1",
                        "01/03/2012",
                        "30"});
            table34.AddRow(new string[] {
                        "colab 2.2",
                        "20/03/2012",
                        "30"});
            table34.AddRow(new string[] {
                        "colab 3.1",
                        "01/02/2012",
                        "90"});
#line 186
       testRunner.And("devem ser listados os planejamentos de ferias:", ((string)(null)), table34, "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07 - Criar planejamento de férias no passado")]
        public virtual void _07_CriarPlanejamentoDeFeriasNoPassado()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07 - Criar planejamento de férias no passado", ((string[])(null)));
#line 194
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "colaborador",
                        "superior",
                        "admissao"});
            table35.AddRow(new string[] {
                        "colab 1",
                        "",
                        "01/01/2011"});
#line 195
    testRunner.Given("que existam os colaboradores:", ((string)(null)), table35, "Dado ");
#line 198
    testRunner.And("data atual for \'20/07/2012\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 199
  testRunner.When("criar planejamento de ferias para o colaborador \'colab 1\' iniciado \'15/07/2012\' n" +
                    "a modalidade \'30\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 200
   testRunner.Then("o planejamento de férias para o colaborador \'colab 1\' iniciado \'15/07/2012\' estar" +
                    "á apto a salvar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
