// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18052
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace WexProject.Test.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class OGerenteDePortifolioPoderAcompanharHistoricoDeUmaSolicitacaoDeOrcamentoFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GerentePortifolioAcompanharHistoricoSolicitacaoOrcamento.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "O Gerente de Portifólio poder Acompanhar Histórico de uma Solicitação de Orçament" +
                    "o", "          Dado um Gerente de Portifólio\r\n\tGostaria de acompanhar o histórico de a" +
                    "lteração das situações da Solicitação de Orçamento\r\n          Então poder visual" +
                    "izar altereções no Documento", ProgrammingLanguage.CSharp, new string[] {
                        "pbi_9.02"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "O Gerente de Portifólio poder Acompanhar Histórico de uma Solicitação de Orçament" +
                            "o")))
            {
                WexProject.Test.Features.OGerenteDePortifolioPoderAcompanharHistoricoDeUmaSolicitacaoDeOrcamentoFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("01 - Colaborador modificar uma SEOT. O histórico deve considerar que o usuário lo" +
            "gado é o responsável pela alteração.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "O Gerente de Portifólio poder Acompanhar Histórico de uma Solicitação de Orçament" +
            "o")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("pbi_9.02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("bug")]
        public virtual void _01_ColaboradorModificarUmaSEOT_OHistoricoDeveConsiderarQueOUsuarioLogadoEOResponsavelPelaAlteracao_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 - Colaborador modificar uma SEOT. O histórico deve considerar que o usuário lo" +
                    "gado é o responsável pela alteração.", new string[] {
                        "bug"});
#line 10
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "descrição"});
            table1.AddRow(new string[] {
                        "P&D de Lei de Informática"});
#line 11
   testRunner.Given("os seguintes tipos de solicitacao de orcamento:", ((string)(null)), table1, "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "documento"});
            table2.AddRow(new string[] {
                        "SolicitacaoOrcamento"});
#line 14
   testRunner.And("as seguintes configuracoes de documento:", ((string)(null)), table2, "E ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "documento",
                        "situação",
                        "cc",
                        "cco",
                        "padrão?"});
            table3.AddRow(new string[] {
                        "SolicitacaoOrcamento",
                        "Não Iniciada",
                        "email@email.com.br;emailtwo@email.com.br",
                        "emailtwo@email.com.br;email@email.com.br",
                        "false"});
#line 17
   testRunner.And("as seguintes situacoes de configuracao de documento:", ((string)(null)), table3, "E ");
#line 20
   testRunner.And("ter colaborador(es) \'colaborador01\',\'colaborador03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "nome",
                        "máscara de telefone",
                        "situação",
                        "país padrão?"});
            table4.AddRow(new string[] {
                        "Brasil",
                        "55 00 0000-0000",
                        "Ativo",
                        "True"});
#line 21
   testRunner.And("os seguintes paises:", ((string)(null)), table4, "E ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "sigla",
                        "nome",
                        "email",
                        "pais",
                        "fone/fax"});
            table5.AddRow(new string[] {
                        "FPF",
                        "Fundação Paulo Feitoza",
                        "fpf@email.com",
                        "Brasil",
                        "55 92 0000-0000"});
#line 24
   testRunner.And("as seguintes empresas/instituicoes:", ((string)(null)), table5, "E ");
#line 27
   testRunner.And("data atual for \'20/02/2012 22:00:00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 28
   testRunner.And("usuario logado for \'colaborador01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "responsável",
                        "situação",
                        "tipo de solicitação",
                        "prioridade",
                        "título",
                        "prazo",
                        "cliente"});
            table6.AddRow(new string[] {
                        "colaborador03",
                        "Não Iniciada",
                        "P&D de Lei de Informática",
                        "Alta",
                        "Desenvolvimento de Aplicativos",
                        "30/11/2012",
                        "FPF"});
#line 29
   testRunner.And("as seguintes solicitacoes de orcamento:", ((string)(null)), table6, "E ");
#line 32
   testRunner.And("data atual for \'22/02/2012 22:00:00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "código",
                        "responsável",
                        "situação",
                        "tipo de solicitação",
                        "prioridade",
                        "título",
                        "prazo",
                        "cliente",
                        "comentário"});
            table7.AddRow(new string[] {
                        "FPF.01/2012",
                        "colaborador03",
                        "Não Iniciada",
                        "P&D de Lei de Informática",
                        "Alta",
                        "Desenvolvimento de Aplicativos",
                        "15/11/2012",
                        "FPF",
                        "Alteração no Prazo da SEOT"});
#line 33
   testRunner.When("as solicitações de orçamento a seguir forem modificadas:", ((string)(null)), table7, "Quando ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "data e hora",
                        "responsavel",
                        "situação",
                        "comentário",
                        "atualizado por"});
            table8.AddRow(new string[] {
                        "20/02/12 22:00:00",
                        "colaborador03",
                        "Não Iniciada",
                        "Criação do Documento",
                        "colaborador01"});
            table8.AddRow(new string[] {
                        "22/02/12 22:00:00",
                        "colaborador03",
                        "Não Iniciada",
                        "Alteração no Prazo da SEOT",
                        "colaborador01"});
#line 36
   testRunner.Then("o historico da solicitacao de orcamento \'FPF.01/2012\' deve ser:", ((string)(null)), table8, "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("02 - Colaborador alterar uma SEOT. Guardar último comentário feito para exibição." +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "O Gerente de Portifólio poder Acompanhar Histórico de uma Solicitação de Orçament" +
            "o")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("pbi_9.02")]
        public virtual void _02_ColaboradorAlterarUmaSEOT_GuardarUltimoComentarioFeitoParaExibicao_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 - Colaborador alterar uma SEOT. Guardar último comentário feito para exibição." +
                    "", ((string[])(null)));
#line 41
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "descrição"});
            table9.AddRow(new string[] {
                        "P&D de Lei de Informática"});
#line 42
   testRunner.Given("os seguintes tipos de solicitacao de orcamento:", ((string)(null)), table9, "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "documento"});
            table10.AddRow(new string[] {
                        "SolicitacaoOrcamento"});
#line 45
   testRunner.And("as seguintes configuracoes de documento:", ((string)(null)), table10, "E ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "documento",
                        "situação",
                        "cc",
                        "cco",
                        "padrão?"});
            table11.AddRow(new string[] {
                        "SolicitacaoOrcamento",
                        "Não Iniciada",
                        "email@email.com.br;emailtwo@email.com.br",
                        "emailtwo@email.com.br;email@email.com.br",
                        "false"});
#line 48
   testRunner.And("as seguintes situacoes de configuracao de documento:", ((string)(null)), table11, "E ");
#line 51
   testRunner.And("ter colaborador(es) \'colaborador01\',\'colaborador03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "nome",
                        "máscara de telefone",
                        "situação",
                        "país padrão?"});
            table12.AddRow(new string[] {
                        "Brasil",
                        "55 00 0000-0000",
                        "Ativo",
                        "True"});
#line 52
   testRunner.And("os seguintes paises:", ((string)(null)), table12, "E ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "sigla",
                        "nome",
                        "email",
                        "pais",
                        "fone/fax"});
            table13.AddRow(new string[] {
                        "FPF",
                        "Fundação Paulo Feitoza",
                        "fpf@email.com",
                        "Brasil",
                        "55 92 0000-0000"});
#line 55
   testRunner.And("as seguintes empresas/instituicoes:", ((string)(null)), table13, "E ");
#line 58
   testRunner.And("data atual for \'20/02/2012 22:00:00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 59
   testRunner.And("usuario logado for \'colaborador01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "responsável",
                        "situação",
                        "tipo de solicitação",
                        "prioridade",
                        "título",
                        "prazo",
                        "cliente"});
            table14.AddRow(new string[] {
                        "colaborador03",
                        "Não Iniciada",
                        "P&D de Lei de Informática",
                        "Alta",
                        "Desenvolvimento de Aplicativos",
                        "30/11/2012",
                        "FPF"});
#line 60
   testRunner.And("as seguintes solicitacoes de orcamento:", ((string)(null)), table14, "E ");
#line 63
   testRunner.And("data atual for \'22/02/2012 22:00:00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "código",
                        "responsável",
                        "situação",
                        "tipo de solicitação",
                        "prioridade",
                        "título",
                        "prazo",
                        "cliente",
                        "comentário"});
            table15.AddRow(new string[] {
                        "FPF.01/2012",
                        "colaborador03",
                        "Não Iniciada",
                        "P&D de Lei de Informática",
                        "Alta",
                        "Desenvolvimento de Aplicativos",
                        "15/11/2012",
                        "FPF",
                        "Alteração no Prazo da SEOT"});
#line 64
   testRunner.When("as solicitações de orçamento a seguir forem modificadas:", ((string)(null)), table15, "Quando ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "código",
                        "último histórico"});
            table16.AddRow(new string[] {
                        "FPF.01/2012",
                        "Alteração no Prazo da SEOT"});
#line 67
   testRunner.Then("o último comentário de alteração das SEOTs devem ser os seguintes:", ((string)(null)), table16, "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("03 - Colaborador criar uma SEOT. O comentário deve ser \'Criação do Documento\'.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "O Gerente de Portifólio poder Acompanhar Histórico de uma Solicitação de Orçament" +
            "o")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("pbi_9.02")]
        public virtual void _03_ColaboradorCriarUmaSEOT_OComentarioDeveSerCriacaoDoDocumento_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 - Colaborador criar uma SEOT. O comentário deve ser \'Criação do Documento\'.", ((string[])(null)));
#line 71
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "descrição"});
            table17.AddRow(new string[] {
                        "P&D de Lei de Informática"});
#line 72
   testRunner.Given("os seguintes tipos de solicitacao de orcamento:", ((string)(null)), table17, "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "documento"});
            table18.AddRow(new string[] {
                        "SolicitacaoOrcamento"});
#line 75
   testRunner.And("as seguintes configuracoes de documento:", ((string)(null)), table18, "E ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "documento",
                        "situação",
                        "cc",
                        "cco",
                        "padrão?"});
            table19.AddRow(new string[] {
                        "SolicitacaoOrcamento",
                        "Não Iniciada",
                        "email@email.com.br;emailtwo@email.com.br",
                        "emailtwo@email.com.br;email@email.com.br",
                        "false"});
#line 78
   testRunner.And("as seguintes situacoes de configuracao de documento:", ((string)(null)), table19, "E ");
#line 81
   testRunner.And("ter colaborador(es) \'colaborador01\',\'colaborador03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "nome",
                        "máscara de telefone",
                        "situação",
                        "país padrão?"});
            table20.AddRow(new string[] {
                        "Brasil",
                        "55 00 0000-0000",
                        "Ativo",
                        "True"});
#line 82
   testRunner.And("os seguintes paises:", ((string)(null)), table20, "E ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "sigla",
                        "nome",
                        "email",
                        "pais",
                        "fone/fax"});
            table21.AddRow(new string[] {
                        "FPF",
                        "Fundação Paulo Feitoza",
                        "fpf@email.com",
                        "Brasil",
                        "55 92 0000-0000"});
#line 85
   testRunner.And("as seguintes empresas/instituicoes:", ((string)(null)), table21, "E ");
#line 88
   testRunner.And("usuario logado for \'colaborador01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "responsável",
                        "situação",
                        "tipo de solicitação",
                        "prioridade",
                        "título",
                        "prazo",
                        "cliente"});
            table22.AddRow(new string[] {
                        "colaborador03",
                        "Não Iniciada",
                        "P&D de Lei de Informática",
                        "Alta",
                        "Desenvolvimento de Aplicativos",
                        "30/11/2012",
                        "FPF"});
#line 89
   testRunner.When("as solicitações de orçamento a seguir forem criadas:", ((string)(null)), table22, "Quando ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "código",
                        "último histórico"});
            table23.AddRow(new string[] {
                        "FPF.01/2012",
                        "Criação do Documento"});
#line 92
   testRunner.Then("o último comentário de alteração das SEOTs devem ser os seguintes:", ((string)(null)), table23, "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("04 - Colaborador modificar uma SEOT. Deve ser o responsável pela atualização.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "O Gerente de Portifólio poder Acompanhar Histórico de uma Solicitação de Orçament" +
            "o")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("pbi_9.02")]
        public virtual void _04_ColaboradorModificarUmaSEOT_DeveSerOResponsavelPelaAtualizacao_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04 - Colaborador modificar uma SEOT. Deve ser o responsável pela atualização.", ((string[])(null)));
#line 96
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "descrição"});
            table24.AddRow(new string[] {
                        "P&D de Lei de Informática"});
#line 97
   testRunner.Given("os seguintes tipos de solicitacao de orcamento:", ((string)(null)), table24, "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "documento"});
            table25.AddRow(new string[] {
                        "SolicitacaoOrcamento"});
#line 100
   testRunner.And("as seguintes configuracoes de documento:", ((string)(null)), table25, "E ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "documento",
                        "situação",
                        "cc",
                        "cco",
                        "padrão?"});
            table26.AddRow(new string[] {
                        "SolicitacaoOrcamento",
                        "Não Iniciada",
                        "email@email.com.br;emailtwo@email.com.br",
                        "emailtwo@email.com.br;email@email.com.br",
                        "false"});
#line 103
   testRunner.And("as seguintes situacoes de configuracao de documento:", ((string)(null)), table26, "E ");
#line 106
   testRunner.And("ter colaborador(es) \'colaborador01\',\'colaborador03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "nome",
                        "máscara de telefone",
                        "situação",
                        "país padrão?"});
            table27.AddRow(new string[] {
                        "Brasil",
                        "55 00 0000-0000",
                        "Ativo",
                        "True"});
#line 107
   testRunner.And("os seguintes paises:", ((string)(null)), table27, "E ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "sigla",
                        "nome",
                        "email",
                        "pais",
                        "fone/fax"});
            table28.AddRow(new string[] {
                        "FPF",
                        "Fundação Paulo Feitoza",
                        "fpf@email.com",
                        "Brasil",
                        "55 92 0000-0000"});
#line 110
   testRunner.And("as seguintes empresas/instituicoes:", ((string)(null)), table28, "E ");
#line 113
   testRunner.And("data atual for \'20/02/2012 22:00:00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 114
   testRunner.And("usuario logado for \'colaborador01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "responsável",
                        "situação",
                        "tipo de solicitação",
                        "prioridade",
                        "título",
                        "prazo",
                        "cliente"});
            table29.AddRow(new string[] {
                        "colaborador03",
                        "Não Iniciada",
                        "P&D de Lei de Informática",
                        "Alta",
                        "Desenvolvimento de Aplicativos",
                        "30/11/2012",
                        "FPF"});
#line 115
   testRunner.And("as seguintes solicitacoes de orcamento:", ((string)(null)), table29, "E ");
#line 118
   testRunner.And("data atual for \'22/02/2012 22:00:00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 119
   testRunner.When("usuario logado for \'colaborador03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "código",
                        "responsável",
                        "situação",
                        "tipo de solicitação",
                        "prioridade",
                        "título",
                        "prazo",
                        "cliente",
                        "comentário"});
            table30.AddRow(new string[] {
                        "FPF.01/2012",
                        "colaborador03",
                        "Não Iniciada",
                        "P&D de Lei de Informática",
                        "Alta",
                        "Desenvolvimento de Aplicativos",
                        "15/11/2012",
                        "FPF",
                        "Alteração no Prazo da SEOT"});
#line 120
   testRunner.And("as solicitações de orçamento a seguir forem modificadas:", ((string)(null)), table30, "E ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "data e hora",
                        "responsavel",
                        "situação",
                        "comentário",
                        "atualizado por"});
            table31.AddRow(new string[] {
                        "20/02/12 22:00:00",
                        "colaborador03",
                        "Não Iniciada",
                        "Criação do Documento",
                        "colaborador01"});
            table31.AddRow(new string[] {
                        "22/02/12 22:00:00",
                        "colaborador03",
                        "Não Iniciada",
                        "Alteração no Prazo da SEOT",
                        "colaborador03"});
#line 123
   testRunner.Then("o historico da solicitacao de orcamento \'FPF.01/2012\' deve ser:", ((string)(null)), table31, "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
