// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.32559
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace WexProject.Test.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Decidir o que fazer com as estórias pendentes do ciclo")]
    [NUnit.Framework.CategoryAttribute("pbi_4.07")]
    public partial class DecidirOQueFazerComAsEstoriasPendentesDoCicloFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "LiderProjetoPoderInformarDestinoEstoriaCiclo.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Decidir o que fazer com as estórias pendentes do ciclo", @"     Como um Líder de Projeto
     Eu quero poder informar se uma estória não concluída será devolvida para lista de prioridades ou movida para o próximo ciclo quando eu encerrar um ciclo
     Para que eu possa ganhar tempo no planejamento dos próximos ciclos", ProgrammingLanguage.CSharp, new string[] {
                        "pbi_4.07"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01 - Definir um ciclo sem estórias pendentes como concluído (RF_4.02)")]
        public virtual void _01_DefinirUmCicloSemEstoriasPendentesComoConcluidoRF_4_02()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 - Definir um ciclo sem estórias pendentes como concluído (RF_4.02)", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
  testRunner.Given("ciclo \'ciclo 01\' na situação \'Em andamento\' com as estórias: \'estória 01\' - situa" +
                    "ção \'Pronto\', \'estória 02\' - situação \'Pronto\', \'estória 03\' - situação \'Pronto\'" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 11
  testRunner.When("definir a situação do ciclo \'ciclo 01\' como \'Concluído\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 12
  testRunner.Then("não deverá exibir a janela de destino das estórias pendentes do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02 - Por padrão, estórias pendentes irão para a lista de \'Próximo Ciclo\' (RF_4.02" +
            ")")]
        public virtual void _02_PorPadraoEstoriasPendentesIraoParaAListaDeProximoCicloRF_4_02()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 - Por padrão, estórias pendentes irão para a lista de \'Próximo Ciclo\' (RF_4.02" +
                    ")", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
  testRunner.Given("um projeto \'projeto 01\' com o(s) ciclo(s) \'ciclo 01\', \'ciclo 02\', \'ciclo 03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 16
  testRunner.And("ciclo \'ciclo 01\' na situação \'Em andamento\' com as estórias: \'estória 01\' - situa" +
                    "ção \'Pronto\', \'estória 02\' - situação \'Não Iniciado\', \'estória 03\' - situação \'E" +
                    "m Desenvolvimento\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 17
  testRunner.When("definir a situação do ciclo \'ciclo 01\' como \'Concluído\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 18
  testRunner.Then("deverá exibir a janela de destino das estórias pendentes do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 19
  testRunner.And("as estórias pendentes do ciclo \'ciclo 01\' deverão ser sugeridas na lista de \'Próx" +
                    "imo Ciclo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03 - Subir a posição de estórias selecionadas (RF_4.02)")]
        public virtual void _03_SubirAPosicaoDeEstoriasSelecionadasRF_4_02()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 - Subir a posição de estórias selecionadas (RF_4.02)", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
  testRunner.Given("um projeto \'projeto 01\' com o(s) ciclo(s) \'ciclo 01\', \'ciclo 02\', \'ciclo 03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 23
  testRunner.And(@"ciclo 'ciclo 01' na situação 'Concluído' com as estórias: 'estória 01' - situação 'Não Iniciado', 'estória 02' - situação 'Em Desenvolvimento', 'estória 03' - situação 'Em Desenvolvimento', 'estória 04' - situação 'Pronto', 'estória 05' - situação 'Não Iniciado', 'estória 06' - situação 'Em Desenvolvimento'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 24
  testRunner.When("selecionar as estórias do ciclo \'ciclo 01\': \'estória 02\', \'estória 03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 25
  testRunner.And("solicitar subir a posição das estórias selecionadas do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 26
  testRunner.Then("todas as estórias selecionadas do ciclo \'ciclo 01\' deverão subir uma posição", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04 - Subir a posição de estórias selecionadas (quando uma das estiver na primeira" +
            " posição) (RF_4.02)")]
        public virtual void _04_SubirAPosicaoDeEstoriasSelecionadasQuandoUmaDasEstiverNaPrimeiraPosicaoRF_4_02()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04 - Subir a posição de estórias selecionadas (quando uma das estiver na primeira" +
                    " posição) (RF_4.02)", ((string[])(null)));
#line 28
this.ScenarioSetup(scenarioInfo);
#line 29
  testRunner.Given("um projeto \'projeto 01\' com o(s) ciclo(s) \'ciclo 01\', \'ciclo 02\', \'ciclo 03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 30
  testRunner.And(@"ciclo 'ciclo 01' na situação 'Concluído' com as estórias: 'estória 01' - situação 'Não Iniciado', 'estória 02' - situação 'Em Desenvolvimento', 'estória 03' - situação 'Em Desenvolvimento', 'estória 04' - situação 'Em Desenvolvimento', 'estória 05' - situação 'Não Iniciado', 'estória 06' - situação 'Em Desenvolvimento'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 31
  testRunner.When("selecionar as estórias do ciclo \'ciclo 01\': \'estória 01\', \'estória 03\', \'estória " +
                    "05\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 32
  testRunner.And("solicitar subir a posição das estórias selecionadas do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 33
  testRunner.Then("a(s) estória(s) \'estória 03\', \'estória 05\' do ciclo \'ciclo 01\' deverá(ão) subir u" +
                    "ma posição", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 34
  testRunner.And("a(s) estória(s) \'estória 01\' do ciclo \'ciclo 01\' deverá(ão) permenecer na mesma p" +
                    "osição, \'subindo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05 - Descer a posição de estórias selecionadas (RF_4.02)")]
        public virtual void _05_DescerAPosicaoDeEstoriasSelecionadasRF_4_02()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 - Descer a posição de estórias selecionadas (RF_4.02)", ((string[])(null)));
#line 36
this.ScenarioSetup(scenarioInfo);
#line 37
  testRunner.Given("um projeto \'projeto 01\' com o(s) ciclo(s) \'ciclo 01\', \'ciclo 02\', \'ciclo 03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 38
  testRunner.And("ciclo \'ciclo 01\' na situação \'Concluído\' com as estórias: \'estória 01\' - situação" +
                    " \'Não Iniciado\', \'estória 02\' - situação \'Em Desenvolvimento\', \'estória 03\' - si" +
                    "tuação \'Em Desenvolvimento\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 39
  testRunner.When("selecionar as estórias do ciclo \'ciclo 01\': \'estória 01\', \'estória 02\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 40
  testRunner.And("solicitar descer a posição das estórias selecionadas do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 41
  testRunner.Then("todas as estórias selecionadas do ciclo \'ciclo 01\' deverão descer uma posição", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06 - Descer a posição de estórias selecionadas (quando uma das estiver na última " +
            "posição) (RF_4.02)")]
        public virtual void _06_DescerAPosicaoDeEstoriasSelecionadasQuandoUmaDasEstiverNaUltimaPosicaoRF_4_02()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06 - Descer a posição de estórias selecionadas (quando uma das estiver na última " +
                    "posição) (RF_4.02)", ((string[])(null)));
#line 43
this.ScenarioSetup(scenarioInfo);
#line 44
  testRunner.Given("um projeto \'projeto 01\' com o(s) ciclo(s) \'ciclo 01\', \'ciclo 02\', \'ciclo 03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 45
  testRunner.And("ciclo \'ciclo 01\' na situação \'Concluído\' com as estórias: \'estória 01\' - situação" +
                    " \'Não Iniciado\', \'estória 02\' - situação \'Em Desenvolvimento\', \'estória 03\' - si" +
                    "tuação \'Em Desenvolvimento\', \'estória 04\' - situação \'Em Desenvolvimento\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 46
  testRunner.When("selecionar as estórias do ciclo \'ciclo 01\': \'estória 01\', \'estória 02\', \'estória " +
                    "04\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 47
  testRunner.And("solicitar descer a posição das estórias selecionadas do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 48
  testRunner.Then("a(s) estória(s) \'estória 01\', \'estória 02\' do ciclo \'ciclo 01\' deverá(ão) descer " +
                    "uma posição", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 49
  testRunner.And("a(s) estória(s) \'estória 04\' do ciclo \'ciclo 01\' deverá(ão) permenecer na mesma p" +
                    "osição, \'descendo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07 - Enviar estórias selecionadas da lista de \'Próximo Ciclo\' para a lista de \'Pr" +
            "ioridades\' (RF_4.02)")]
        public virtual void _07_EnviarEstoriasSelecionadasDaListaDeProximoCicloParaAListaDePrioridadesRF_4_02()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07 - Enviar estórias selecionadas da lista de \'Próximo Ciclo\' para a lista de \'Pr" +
                    "ioridades\' (RF_4.02)", ((string[])(null)));
#line 51
this.ScenarioSetup(scenarioInfo);
#line 52
  testRunner.Given("ciclo \'ciclo 01\' na situação \'Em andamento\' com as estórias: \'estória 01\' - situa" +
                    "ção \'Não Iniciado\', \'estória 02\' - situação \'Em Desenvolvimento\', \'estória 03\' -" +
                    " situação \'Em Desenvolvimento\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 53
  testRunner.And("todas as estórias do ciclo \'ciclo 01\' estiverem na lista de \'Próximo Ciclo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 54
  testRunner.When("selecionar as estórias da lista de \'Próximo Ciclo\' do ciclo \'ciclo 01\': \'estória " +
                    "01\', \'estória 02\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 55
  testRunner.And("solicitar enviar estórias da lista de \'Próximo Ciclo\' para a lista de \'Prioridade" +
                    "s\' do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 56
  testRunner.Then("todas as estórias selecionadas deverão sair da lista de \'Próximo Ciclo\' e irão pa" +
                    "ra a lista de \'Prioridades\' do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08 - Enviar estórias selecionadas da lista de \'Prioridades\' para a lista de \'Próx" +
            "imo Ciclo\' (RF_4.02)")]
        public virtual void _08_EnviarEstoriasSelecionadasDaListaDePrioridadesParaAListaDeProximoCicloRF_4_02()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08 - Enviar estórias selecionadas da lista de \'Prioridades\' para a lista de \'Próx" +
                    "imo Ciclo\' (RF_4.02)", ((string[])(null)));
#line 58
this.ScenarioSetup(scenarioInfo);
#line 59
  testRunner.Given("ciclo \'ciclo 01\' na situação \'Em andamento\' com as estórias: \'estória 01\' - situa" +
                    "ção \'Não Iniciado\', \'estória 02\' - situação \'Em Desenvolvimento\', \'estória 03\' -" +
                    " situação \'Em Desenvolvimento\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 60
  testRunner.And("todas as estórias do ciclo \'ciclo 01\' estiverem na lista de \'Prioridades\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 61
  testRunner.When("selecionar as estórias da lista de \'Prioridades\' do ciclo \'ciclo 01\': \'estória 01" +
                    "\', \'estória 02\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 62
  testRunner.And("solicitar enviar estórias da lista de \'Prioridades\' para a lista de \'Próximo Cicl" +
                    "o\' do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 63
  testRunner.Then("todas as estórias selecionadas deverão sair da lista de \'Prioridades\' e irão para" +
                    " a lista de \'Próximo Ciclo\' do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("09 - Enviar todas as estórias da lista de \'Próximo Ciclo\' para a lista de \'Priori" +
            "dades\' (RF_4.02)")]
        public virtual void _09_EnviarTodasAsEstoriasDaListaDeProximoCicloParaAListaDePrioridadesRF_4_02()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09 - Enviar todas as estórias da lista de \'Próximo Ciclo\' para a lista de \'Priori" +
                    "dades\' (RF_4.02)", ((string[])(null)));
#line 65
this.ScenarioSetup(scenarioInfo);
#line 66
  testRunner.Given("ciclo \'ciclo 01\' na situação \'Em andamento\' com as estórias: \'estória 01\' - situa" +
                    "ção \'Não Iniciado\', \'estória 02\' - situação \'Em Desenvolvimento\', \'estória 03\' -" +
                    " situação \'Em Desenvolvimento\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 67
  testRunner.And("todas as estórias do ciclo \'ciclo 01\' estiverem na lista de \'Próximo Ciclo\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 68
  testRunner.When("solicitar enviar todas as estórias da lista de \'Próximo Ciclo\' para a lista de \'P" +
                    "rioridades\' do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 69
  testRunner.Then("todas as estórias selecionadas deverão sair da lista de \'Próximo Ciclo\' e irão pa" +
                    "ra a lista de \'Prioridades\' do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 70
  testRunner.And("a lista de \'Próximo Ciclo\' do ciclo \'ciclo 01\' deve estar vazia", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10 - Enviar todas as estórias da lista de \'Prioridades\' para a lista de \'Próximo " +
            "Ciclo\' (RF_4.02)")]
        public virtual void _10_EnviarTodasAsEstoriasDaListaDePrioridadesParaAListaDeProximoCicloRF_4_02()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10 - Enviar todas as estórias da lista de \'Prioridades\' para a lista de \'Próximo " +
                    "Ciclo\' (RF_4.02)", ((string[])(null)));
#line 72
this.ScenarioSetup(scenarioInfo);
#line 73
  testRunner.Given("ciclo \'ciclo 01\' na situação \'Em andamento\' com as estórias: \'estória 01\' - situa" +
                    "ção \'Não Iniciado\', \'estória 02\' - situação \'Em Desenvolvimento\', \'estória 03\' -" +
                    " situação \'Em Desenvolvimento\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 74
  testRunner.And("todas as estórias do ciclo \'ciclo 01\' estiverem na lista de \'Prioridades\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 75
  testRunner.When("solicitar enviar todas as estórias da lista de \'Prioridades\' para a lista de \'Pró" +
                    "ximo Ciclo\' do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 76
  testRunner.Then("todas as estórias selecionadas deverão sair da lista de \'Prioridades\' e irão para" +
                    " a lista de \'Próximo Ciclo\' do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 77
  testRunner.And("a lista de \'Prioridades\' do ciclo \'ciclo 01\' deve estar vazia", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11 - Salvar o destino das estórias pendentes (RF_4.02)")]
        public virtual void _11_SalvarODestinoDasEstoriasPendentesRF_4_02()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11 - Salvar o destino das estórias pendentes (RF_4.02)", ((string[])(null)));
#line 79
this.ScenarioSetup(scenarioInfo);
#line 80
  testRunner.Given("um projeto \'projeto 01\' com o(s) ciclo(s) \'ciclo 01\', \'ciclo 02\', \'ciclo 03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 81
  testRunner.And("ciclo \'ciclo 01\' na situação \'Em andamento\' com as estórias: \'estória 01\' - situa" +
                    "ção \'Não Iniciado\', \'estória 02\' - situação \'Em Desenvolvimento\', \'estória 03\' -" +
                    " situação \'Em Desenvolvimento\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 82
  testRunner.When("definir a situação do ciclo \'ciclo 01\' como \'Concluído\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 83
  testRunner.And("a(s) estória(s) \'estória 01\' estiver(em) na lista de \'Prioridades\' do ciclo \'cicl" +
                    "o 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 84
  testRunner.And("a(s) estória(s) \'estória 02\', \'estória 03\' estiver(em) na lista de \'Próximo Ciclo" +
                    "\' do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 85
  testRunner.And("salvar o destino das estórias pentendes do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 86
  testRunner.Then("a(s) estória(s) \'estória 01\' deve(m) ser movidas para o backlog", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 87
  testRunner.And("a(s) estória(s) \'estória 02\', \'estória 03\' deve(m) estar como \'Replanejado\' no ci" +
                    "clo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 88
  testRunner.And("a(s) estória(s) \'estória 02\', \'estória 03\' deve(m) estar como \'Não Iniciado\' no c" +
                    "iclo \'ciclo 02\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("12 - Salvar o destino das estórias pendentes (último ciclo) (RF_4.02)")]
        public virtual void _12_SalvarODestinoDasEstoriasPendentesUltimoCicloRF_4_02()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("12 - Salvar o destino das estórias pendentes (último ciclo) (RF_4.02)", ((string[])(null)));
#line 90
this.ScenarioSetup(scenarioInfo);
#line 91
  testRunner.Given("um projeto \'projeto 01\' com o(s) ciclo(s) \'ciclo 01\', \'ciclo 02\', \'ciclo 03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 92
  testRunner.And("ciclo \'ciclo 03\' na situação \'Em andamento\' com as estórias: \'estória 01\' - situa" +
                    "ção \'Não Iniciado\', \'estória 02\' - situação \'Em Desenvolvimento\', \'estória 03\' -" +
                    " situação \'Em Desenvolvimento\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 93
  testRunner.When("definir a situação do ciclo \'ciclo 03\' como \'Concluído\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 94
  testRunner.Then("não deverá exibir a janela de destino das estórias pendentes do ciclo \'ciclo 03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 95
  testRunner.And("a(s) estória(s) \'estória 01\', \'estória 02\' deve(m) estar como \'Replanejado\' no ci" +
                    "clo \'ciclo 03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 96
  testRunner.And("a(s) estória(s) \'estória 01\', \'estória 02\', \'estória 03\' deve(m) ser movidas para" +
                    " o backlog", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("13 - Salvar o destino das estórias pendentes (próximo ciclo concluído) (RF_4.02)")]
        public virtual void _13_SalvarODestinoDasEstoriasPendentesProximoCicloConcluidoRF_4_02()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("13 - Salvar o destino das estórias pendentes (próximo ciclo concluído) (RF_4.02)", ((string[])(null)));
#line 98
this.ScenarioSetup(scenarioInfo);
#line 99
  testRunner.Given("um projeto \'projeto 01\' com o(s) ciclo(s) \'ciclo 01\', \'ciclo 02\', \'ciclo 03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 100
  testRunner.And("ciclo \'ciclo 01\' na situação \'Em andamento\' com as estórias: \'estória 01\' - situa" +
                    "ção \'Não Iniciado\', \'estória 02\' - situação \'Em Desenvolvimento\', \'estória 03\' -" +
                    " situação \'Em Desenvolvimento\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 101
  testRunner.And("ciclo \'ciclo 02\' na situação \'Concluído\' com as estórias: \'estória 04\' - situação" +
                    " \'Pronto\', \'estória 05\' - situação \'Pronto\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 102
  testRunner.When("definir a situação do ciclo \'ciclo 01\' como \'Concluído\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 103
  testRunner.And("a(s) estória(s) \'estória 02\', \'estória 03\' estiver(em) na lista de \'Próximo Ciclo" +
                    "\' do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 104
  testRunner.And("a(s) estória(s) \'estória 01\' estiver(em) na lista de \'Prioridades\' do ciclo \'cicl" +
                    "o 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 105
  testRunner.And("salvar o destino das estórias pentendes do ciclo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 106
  testRunner.Then("a(s) estória(s) \'estória 01\' deve(m) ser movidas para o backlog", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 107
  testRunner.And("a(s) estória(s) \'estória 02\', \'estória 03\' deve(m) estar como \'Replanejado\' no ci" +
                    "clo \'ciclo 01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 108
  testRunner.And("a(s) estória(s) \'estória 02\', \'estória 03\' deve(m) estar como \'Não Iniciado\' no c" +
                    "iclo \'ciclo 03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
